function numberChecker(num) {
  if (num > 20) { //Si 50 (que es la variable declarada abajo) es mayor que 20...
    return `${num} is greater than 20`; // Imprime este mensaje...
  } else if (num === 20) { // Si no, verifica que esa variable sea igual en tipo o número a 20...
    return `${num} is equal to 20`; //Impirme este mensaje...
  } else if (num < 20) { // Si no, verifica si la variable es menor a 20...
    return `${num} is less than 20`; //Imprime este mensaje...
  } else { //Si no es ninguna de las anteriores...
    return `${num} isn't even a number :(`; //Imprime este mensaje.
  }
}

//console.log(numberChecker("hola"));
console.log(numberChecker(50));